# generated by datamodel-codegen:
#   filename:  common.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field


class Role(StrEnum):
    """
    The speaker of a single message in a conversation.
    """

    system = 'system'
    user = 'user'
    assistant = 'assistant'
    hemisphere = 'hemisphere'


class Message(BaseModel):
    """
    A single message in an Eugene Plexus conversation. The shape is
    deliberately close to the OpenAI / Anthropic chat message format so
    that adapters don't have to re-shape on every hop, but `role` includes
    `hemisphere` for messages emitted by one of the parallel drivers
    during a bicameral pass (visible to corpus callosum and UI debug
    views, not normally to the end user).

    """

    role: Role
    content: str = Field(
        ...,
        description='Message text. v0.1 is text-only; multimodal extensions deferred.',
    )
    driverName: str | None = Field(
        None,
        description='When `role == "hemisphere"`, the operator-supplied name of\nthe driver that produced this message (e.g. `"left"`,\n`"right"`, or any free-form label set by the orchestrator\'s\n`drivers` config). Omitted otherwise. Identity is owned by\nthe orchestrator\'s topology config — drivers themselves do\nnot know their position in the pair.\n',
    )
    timestamp: AwareDatetime | None = Field(
        None, description='When the message was produced. Server-assigned if omitted.'
    )
    passIndex: int | None = Field(
        None,
        description='Zero-based index of the bicameral pass that produced this message.\nPass 0 is the initial hemisphere response; subsequent passes are\nre-prompts after corpus-callosum disagreement.\n',
        ge=0,
    )


class Conversation(BaseModel):
    """
    An ordered list of messages constituting a conversation history.
    """

    id: UUID | None = Field(None, description='Server-assigned conversation id.')
    messages: list[Message]


class NTState(BaseModel):
    """
    A snapshot of Eugene's neurotransmitter state. v0.1 wires this through
    the schemas but does not modulate behavior on it — the framework
    passes a static neutral state. Drives, plasticity, and modulation
    come in v0.2+.

    Values are in [0, 1]. 0.5 represents a baseline / neutral level.

    """

    serotonin: float | None = Field(
        None,
        description='Mood / satiation tone. High = content / patient.',
        ge=0.0,
        le=1.0,
    )
    dopamine: float | None = Field(
        None,
        description='Reward prediction / motivation. High = engaged / curious.',
        ge=0.0,
        le=1.0,
    )
    norepinephrine: float | None = Field(
        None,
        description='Arousal / vigilance. High = alert / focused under load.',
        ge=0.0,
        le=1.0,
    )
    acetylcholine: float | None = Field(
        None,
        description='Attention / encoding gain. High = sharp focus, fast learning.',
        ge=0.0,
        le=1.0,
    )
    gaba: float | None = Field(
        None, description='Inhibitory tone. High = calm / restrained.', ge=0.0, le=1.0
    )
    glutamate: float | None = Field(
        None,
        description='Excitatory drive. High = active / responsive.',
        ge=0.0,
        le=1.0,
    )


class DriverEntry(BaseModel):
    """
    One operator-configured hemisphere-driver in the orchestrator's
    topology. The orchestrator owns the `name` (free-form, used for
    labelling messages and UI tabs); drivers themselves are anonymous
    and report only their backend / model identity. v0.1 expects two
    entries; v0.2+ generalizes to N (with backup/failover semantics
    layered on top).

    """

    name: str = Field(
        ...,
        description='Operator-supplied label (e.g. `"left"`, `"right"`, or any\nfree-form string). Stamped onto every message this driver\nproduces and surfaced in the UI as the tab/column label.\n',
        min_length=1,
    )
    url: AnyUrl = Field(
        ..., description="Base URL where the driver's HTTP API is reachable."
    )


class BackendKind(StrEnum):
    """
    Which adapter the hemisphere-driver instance is configured to use.
    Reported by `/v1/info` so the orchestrator can log and the UI can
    render a label. `claude_code_cli` and `codex_cli` shell out to the
    respective CLIs (primary mode for personal installations).

    """

    anthropic_api = 'anthropic_api'
    openai_api = 'openai_api'
    claude_code_cli = 'claude_code_cli'
    codex_cli = 'codex_cli'
    openai_compat_http = 'openai_compat_http'


class Problem(BaseModel):
    """
    Error response shape, modeled on RFC 7807 (problem+json). Every
    Eugene Plexus component returns this for 4xx / 5xx responses.

    """

    type: str = Field(
        ...,
        description='A URI reference identifying the problem type, per RFC 7807.\nModeled as a plain string rather than `format: uri` to keep\nsentinel values like `about:blank` and ergonomic at call sites.\n',
    )
    title: str = Field(..., description='Short human-readable summary.')
    status: int = Field(..., description='HTTP status code.')
    detail: str | None = Field(
        None, description='Human-readable explanation specific to this occurrence.'
    )
    instance: str | None = Field(
        None,
        description='A URI reference identifying the specific occurrence. Modeled\nas a plain string for the same reason as `type`.\n',
    )
    component: str | None = Field(
        None,
        description='Eugene Plexus component name that originated the error\n(e.g. `"orchestrator"`, `"hemisphere-driver:left"`).\n',
    )


class Status(StrEnum):
    ok = 'ok'
    degraded = 'degraded'
    error = 'error'


class Health(BaseModel):
    """
    Liveness / readiness response shape.
    """

    status: Status
    version: str | None = Field(None, description='Component version (semver).')
    component: str | None = Field(
        None, description='Component identifier (e.g. `"hemisphere-driver"`).'
    )
    safeMode: bool | None = Field(
        False,
        description="True when the component was started with the watchdog's\nsafe-mode env var set\n(`EUGENE_PLEXUS_<KIND>_SAFE_MODE=1`) and is therefore\nrunning on built-in defaults instead of its persisted\nconfig. Components in safe mode are reachable for config\nediting (`PATCH /v1/config` writes to disk normally) but\nshould be considered non-functional for their primary\npurpose until restarted without the flag. `status` is\nalso reported as `degraded` while safe mode is in effect.\n",
    )
    details: dict[str, Any] | None = Field(
        None, description='Optional component-specific health detail.'
    )


class ConfigValueType(StrEnum):
    """
    The kind of value a config field holds. The UI uses this to pick
    a renderer (text input, dropdown, password field, etc.).

    """

    string = 'string'
    integer = 'integer'
    number = 'number'
    boolean = 'boolean'
    enum = 'enum'
    secret = 'secret'
    file_path = 'file_path'
    url = 'url'
    duration = 'duration'
    driver_list = 'driver_list'


class ConfigFieldShowWhen(BaseModel):
    """
    Predicate over another `ConfigField`'s current value. The UI
    renders the field this is attached to only when the named field
    equals the given value (or matches one entry in the given list).

    """

    key: str = Field(
        ...,
        description='`key` of another field in the same `ConfigSchema` to compare\nagainst.\n',
    )
    equals: Any = Field(
        ...,
        description="Value the named field must equal for this field to render.\nUntyped — when scalar, matches by literal equality against\nthe referenced field's `valueType`. When an array, matches\nif the referenced field's current value equals any entry\n(set-membership). Use the array form for a field that\napplies to multiple entries of an enum (e.g. an `apiKey`\nfield shared across several OpenAI-compatible providers).\n",
    )


class ConfigDocument(BaseModel):
    """
    Current effective config values, keyed by `ConfigField.key`.
    Values of fields with `sensitive: true` are returned as the
    literal string `"<redacted>"` regardless of whether they are
    set. Returned by `GET /v1/config`.

    """

    model_config = ConfigDict(
        extra='allow',
    )


class ConfigUpdateRequest(BaseModel):
    """
    Partial update for `PATCH /v1/config`. Every present key is
    set; absent keys are left unchanged. To revert a field to its
    default, send `null` as the value. Sensitive fields are written
    through directly (the redacted form sent back by GET is never
    accepted as a write value).

    """

    model_config = ConfigDict(
        extra='allow',
    )


class ConfigFieldError(BaseModel):
    """
    A per-field validation failure during PATCH.
    """

    key: str
    message: str


class ConfigUpdateResult(BaseModel):
    """
    Outcome of a `PATCH /v1/config` call. Validation failures on
    individual keys do not abort the whole request — valid changes
    are applied, invalid ones are reported in `rejected`.

    """

    applied: list[str] = Field(
        ..., description='Keys that were validated and applied successfully.'
    )
    rejected: list[ConfigFieldError] = Field(
        ...,
        description='Keys whose new values failed validation. The current value\nis preserved.\n',
    )
    requiresRestart: bool = Field(
        ...,
        description='True if any key in `applied` has `requiresRestart: true`,\nmeaning a process restart is needed for the change to take\neffect. The UI should surface this to the user.\n',
    )
    pendingRestart: list[str] | None = Field(
        None,
        description='Keys whose new values are stored but not yet active. Subset\nof `applied`. Empty unless `requiresRestart` is true.\n',
    )


class ConfigTestRequest(BaseModel):
    """
    Optional override for `POST /v1/config/test`. Same shape as
    `ConfigUpdateRequest`: keys override the saved config for the
    duration of the test only. Useful for "Test Connection" UIs where
    the operator wants to verify a new API key, URL, or model
    identifier before committing it. Send an empty body (`{}`) to
    test the saved config as-is.

    """

    overrides: ConfigUpdateRequest | None = None


class ConfigTestResult(BaseModel):
    """
    Result of a `POST /v1/config/test` invocation. Components decide
    what "test" means for their own surface: hemisphere-driver runs
    a minimal `generate()` round-trip; orchestrator probes its
    configured hemispheres + memory; memory verifies the store
    backend is reachable.

    """

    ok: bool = Field(
        ..., description='True iff the test invocation succeeded end-to-end.'
    )
    component: str = Field(
        ...,
        description='Component identifier (matches `ConfigSchema.component`).\nEchoed for UI clarity when several /v1/config/test responses\nland in the same view.\n',
    )
    latencyMs: int = Field(
        ..., description='Wall-clock time the test took, in milliseconds.'
    )
    summary: str | None = Field(
        None,
        description='One-line human-readable result summary. Always set when\n`ok` is true; may be set on failure to add context beyond\n`error`.\n',
    )
    sampleOutput: str | None = Field(
        None,
        description="Brief sample of the data the test produced — e.g. assistant\ntext from a hemisphere-driver `generate()` round-trip. May be\ntruncated to keep the response small. Omitted when there's\nnothing useful to show.\n",
    )
    error: str | None = Field(
        None,
        description='Human-readable error message. Set when `ok` is false. Should\nbe specific enough that the operator can act on it (e.g.\n`"openaiApiKey rejected: 401 Unauthorized"`).\n',
    )


class RestartResult(BaseModel):
    """
    Acknowledgement returned by `POST /v1/admin/restart`. The
    component schedules its own process exit shortly after returning
    this response (typically a few hundred ms — long enough for the
    HTTP response to flush). The component does NOT bring itself
    back up; a process supervisor (systemd, docker-compose, the
    deploy launcher, etc.) is expected to relaunch it. In v0.1
    personal-use deploys without a supervisor, the operator
    relaunches manually.

    """

    scheduled: bool = Field(
        ...,
        description='True if the component accepted the restart and an exit is\nqueued. Always true in v0.1 — the endpoint has no reason to\nrefuse — but typed as a boolean so future versions can gate\non (e.g.) an in-flight long-running operation.\n',
    )
    delayMs: int = Field(
        ...,
        description='How long the component intends to wait before calling exit,\nmeasured from the moment the response is sent. Lets clients\ntime their UI ("restarting in 0.5s…") and decide when to\nstart polling `/healthz` for the relaunched process.\n',
        ge=0,
    )
    message: str | None = Field(
        None,
        description='Optional human-readable note (e.g. "logs flushed, exiting\nnow"). UI may display this in the restart-progress dialog.\n',
    )


class ConfigField(BaseModel):
    """
    UI-renderable description of a single editable config field.

    """

    key: str = Field(
        ...,
        description='Stable machine-readable id, dot-separated for grouping\n(e.g. `"adapter.modelId"`).\n',
    )
    label: str = Field(..., description='Human-readable label for the UI.')
    description: str | None = Field(
        None, description='One-sentence explanation suitable for non-programmers.'
    )
    category: str = Field(
        ...,
        description='Group key for UI tabbing or sectioning (e.g. `"adapter"`,\n`"logging"`, `"network"`). Mapped to a display label via\n`ConfigSchema.categories`.\n',
    )
    valueType: ConfigValueType
    default: Any | None = Field(
        None,
        description='Default value if unset. Type matches `valueType`. Omitted\nfor fields with no default.\n',
    )
    enumValues: list[str] | None = Field(
        None, description='Allowed values when `valueType == enum`.'
    )
    enumLabels: list[str] | None = Field(
        None,
        description='Optional human-readable display labels paired one-to-one\nwith `enumValues`. UIs that render an enum as a dropdown\nshould show `enumLabels[i]` while still submitting\n`enumValues[i]` as the saved value. When omitted (or\nshorter than `enumValues`), UIs fall back to the raw\nvalue as the label. Useful where the stored key is\nmachine-friendly but the user-facing label isn\'t —\ne.g. `claude_subscription` saved, "Claude (Pro/Max)"\nshown.\n',
    )
    sensitive: bool | None = Field(
        False,
        description='If true, the value is redacted (`"<redacted>"`) in\n`ConfigDocument` responses but is accepted in\n`ConfigUpdateRequest`. Use for API keys, passwords, etc.\n',
    )
    required: bool | None = Field(
        False,
        description='If true, the component will refuse to start without this\nfield set (either in config or via env var fallback).\n',
    )
    minimum: float | None = Field(
        None, description='Validation hint for `integer` / `number` fields.'
    )
    maximum: float | None = Field(
        None, description='Validation hint for `integer` / `number` fields.'
    )
    pattern: str | None = Field(
        None, description='Regex validation hint for `string` / `url` / `file_path`.'
    )
    requiresRestart: bool | None = Field(
        False,
        description='If true, changes to this field via PATCH are accepted and\nstored but do not take effect until the component process\nrestarts. The UI should warn before submitting.\n',
    )
    showWhen: ConfigFieldShowWhen | None = Field(
        None,
        description="Conditional-rendering hint. When set, the UI should only\nrender this field when another field's current value matches\nthe condition. Used to hide adapter-specific fields\n(e.g. `openaiApiKey`) when a different adapter is selected.\nThe component still validates and stores the field\nregardless of UI visibility.\n",
    )


class ConfigSchema(BaseModel):
    """
    UI-renderable description of every editable config field this
    component accepts. Returned by `GET /v1/config/schema`. UIs use
    this to render a generic config editor without component-specific
    code.

    """

    component: str = Field(
        ..., description='Component identifier (e.g. `"hemisphere-driver"`).'
    )
    fields: list[ConfigField]
    categories: dict[str, str] | None = Field(
        None,
        description='Map from category key (used in `ConfigField.category`) to\na human-readable section label. Optional; UIs may fall back\nto the raw key.\n',
    )
