# generated by datamodel-codegen:
#   filename:  watchdog.yaml

from __future__ import annotations

from enum import StrEnum

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field


class ComponentKind(StrEnum):
    """
    Which Eugene Plexus component class this entry represents. The
    watchdog's spawn registry maps each kind to a launch command.
    v0.1 covered three body parts (orchestrator, hemisphere-driver,
    memory); v0.2 adds `identity` (the Default Mode Network — see
    `openapi/identity.yaml`). The `connector` kind lands later in
    v0.2 once the connector repo exists.

    """

    orchestrator = 'orchestrator'
    hemisphere_driver = 'hemisphere-driver'
    memory = 'memory'
    identity = 'identity'


class SpawnConfig(BaseModel):
    configFile: str = Field(
        ...,
        description="Absolute path to the component's own config file. The\nwatchdog passes this to the component via its\nkind-specific env var\n(`EUGENE_PLEXUS_<KIND>_CONFIG_FILE`) at spawn time.\n",
    )
    env: dict[str, str] | None = Field(
        None,
        description='Optional extra environment variables to pass to the\nspawned process. Reserved for advanced operators; the\nwizard never sets this.\n',
    )


class ComponentStatus(StrEnum):
    """
    Current operational state.

    * `starting` — watchdog has spawned the process but it has
      not yet answered `/healthz`.
    * `running` — process is up and `/healthz` is healthy.
    * `safe_mode` — process is up but launched with
      `SAFE_MODE=1`; will refuse to do useful work until the
      operator fixes its config and clears the safe-mode flag.
    * `exited` — process exited cleanly and the watchdog is in
      the middle of respawning it (transient state).
    * `crashed` — process has exited non-zero repeatedly and the
      watchdog has given up auto-restarting it. Operator must
      restart it manually after fixing the cause.
    * `unreachable` — for remote components, the watchdog can't
      reach the URL. For spawned components this state is not
      used (use `crashed` or `exited` instead).

    """

    starting = 'starting'
    running = 'running'
    safe_mode = 'safe_mode'
    exited = 'exited'
    crashed = 'crashed'
    unreachable = 'unreachable'


class Component(BaseModel):
    """
    Combined declarative + operational view of one supervised
    component. The declarative half (`name`, `kind`, `url`,
    `spawn`, `safeMode`) is what's persisted to `watchdog.yaml`.
    The operational half (`status`, `lastRestart`, `lastError`,
    `pid`) is observed at runtime and not persisted.

    """

    name: str = Field(
        ...,
        description="Operator-supplied label, also used in the orchestrator's `drivers` list.",
    )
    kind: ComponentKind
    url: AnyUrl = Field(
        ...,
        description='Canonical address. For spawned components the watchdog\nparses the port out of this URL and passes it via env var\n(`EUGENE_PLEXUS_<KIND>_BIND_PORT`); for remote components\nthis is what the watchdog probes.\n',
    )
    spawn: SpawnConfig | None = Field(
        None,
        description="Present iff this component runs locally under watchdog\nsupervision. Absence means it's remote (the watchdog only\nmonitors reachability).\n",
    )
    safeMode: bool | None = Field(
        False,
        description='When true the watchdog launches the spawned component with\n`EUGENE_PLEXUS_<KIND>_SAFE_MODE=1`, telling it to ignore its\nown config file and boot from defaults. Used to recover\nfrom a config that breaks startup. Ignored for remote\ncomponents.\n',
    )
    status: ComponentStatus
    pid: int | None = Field(
        None,
        description='Operating-system process id. Set only for spawned, currently-running components.',
    )
    lastRestart: AwareDatetime | None = Field(
        None, description='When the watchdog last started or restarted this component.'
    )
    lastError: str | None = Field(
        None,
        description="Most recent error observed for this component. Reset to null\non successful restart. Useful for surfacing why a component\nkeeps crashing in the UI's Components tab.\n",
    )


class ComponentEntry(BaseModel):
    """
    Declarative half of a Component, used for create / update
    request bodies. Status fields are server-owned and excluded.

    """

    name: str
    kind: ComponentKind
    url: AnyUrl
    spawn: SpawnConfig | None = None
    safeMode: bool | None = False


class ComponentList(BaseModel):
    components: list[Component] = Field(
        ...,
        description='Components in the order they were configured. The first-run\nwizard fills this in; later editing happens via the\nComponents tab.\n',
    )
