# generated by datamodel-codegen:
#   filename:  watchdog.yaml

from __future__ import annotations

from enum import IntEnum, StrEnum
from typing import Any
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field


class ComponentKind(StrEnum):
    """
    Which Eugene Plexus component class a topology entry represents.
    Lives in `common.yaml` because multiple components reference it:
    the watchdog's `/v1/components`, and (via `ConfigField.
    componentKindHint`) any component declaring a config field that
    points at a peer of a specific kind. v0.1 covered three body
    parts (orchestrator, hemisphere-driver, memory); v0.2 adds
    `identity` (Default Mode Network analogue) and `connector`
    (external sense organs).

    v0.3 adds the local-LLM-platform components: `coordinator`
    (owns the `TrainingProject` aggregate and sequences pipeline
    runs across the others), `trainer` (executes training runs +
    owns checkpoints), `data` (datasets + tokenizers),
    `eval` (eval suites + results), `inference` (OpenAI-compatible
    local serving), and `cluster` (deferred; multi-host workers).

    """

    orchestrator = 'orchestrator'
    hemisphere_driver = 'hemisphere-driver'
    memory = 'memory'
    identity = 'identity'
    connector = 'connector'
    coordinator = 'coordinator'
    trainer = 'trainer'
    data = 'data'
    eval = 'eval'
    inference = 'inference'
    cluster = 'cluster'


class Role(StrEnum):
    """
    The speaker of a single message in a conversation.
    """

    system = 'system'
    user = 'user'
    assistant = 'assistant'
    hemisphere = 'hemisphere'


class Message(BaseModel):
    """
    A single message in an Eugene Plexus conversation. The shape is
    deliberately close to the OpenAI / Anthropic chat message format so
    that adapters don't have to re-shape on every hop, but `role` includes
    `hemisphere` for messages emitted by one of the parallel drivers
    during a bicameral pass (visible to corpus callosum and UI debug
    views, not normally to the end user).

    """

    role: Role
    content: str = Field(
        ...,
        description='Message text. v0.1 is text-only; multimodal extensions deferred.',
    )
    driverName: str | None = Field(
        None,
        description='When `role == "hemisphere"`, the operator-supplied name of\nthe driver that produced this message (e.g. `"left"`,\n`"right"`, or any free-form label set by the orchestrator\'s\n`drivers` config). Omitted otherwise. Identity is owned by\nthe orchestrator\'s topology config — drivers themselves do\nnot know their position in the pair.\n',
    )
    timestamp: AwareDatetime | None = Field(
        None, description='When the message was produced. Server-assigned if omitted.'
    )
    passIndex: int | None = Field(
        None,
        description='Zero-based index of the bicameral pass that produced this message.\nPass 0 is the initial hemisphere response; subsequent passes are\nre-prompts after corpus-callosum disagreement.\n',
        ge=0,
    )


class Conversation(BaseModel):
    """
    An ordered list of messages constituting a conversation history.
    """

    id: UUID | None = Field(None, description='Server-assigned conversation id.')
    messages: list[Message]


class NTLevel(BaseModel):
    """
    Per-NT level + its baseline + per-second decay rate. The level
    decays toward baseline at `decay` units per second between
    observations; observations push it up or down based on the
    orchestrator's observation→NT mapping (see orchestrator spec).

    """

    level: float = Field(
        ..., description='Current instantaneous value.', ge=0.0, le=1.0
    )
    baseline: float = Field(
        ..., description='Resting-state target the level decays toward.', ge=0.0, le=1.0
    )
    decay: float = Field(
        ...,
        description='Per-second decay rate toward baseline. Larger values =\nfaster return to baseline after a stimulus.\n',
        ge=0.0,
        le=1.0,
    )


class DriverEntry(BaseModel):
    """
    One operator-configured hemisphere-driver *slot* in the
    orchestrator's topology. The orchestrator owns the `name`
    (free-form, used for labelling messages and UI tabs); drivers
    themselves are anonymous and report only their backend / model
    identity. The bicameral loop requires exactly two slots.

    A slot is a **priority list** of backends (`backends`), not a
    single backend. Each entry is the NAME of a hemisphere-driver
    entry in the watchdog topology (`GET /v1/components`,
    `kind: hemisphere-driver`); the orchestrator resolves names to
    URLs at startup. This keeps backend URLs in exactly one place
    (the watchdog topology) instead of duplicating them into the
    orchestrator's config (v0.2.1).

    On each chat turn the orchestrator tries `backends[0]`; if it
    fails in a cascade-eligible way (transport error / 5xx /
    timeout) it falls through to `backends[1]`, and so on. A 4xx
    fails the slot HARD without cascading — a 4xx is a
    request/auth/config bug that the next backend would hit
    identically, and cascading past it would mask the real problem.
    Stock installs run one backend per slot.

    """

    name: str = Field(
        ...,
        description='Operator-supplied label (e.g. `"left"`, `"right"`, or any\nfree-form string). Stamped onto every message this slot\nproduces and surfaced in the UI as the tab/column label.\n',
        min_length=1,
    )
    backends: list[str] = Field(
        ...,
        description='Ordered priority list of watchdog-topology hemisphere-driver\nentry NAMES that back this slot. The orchestrator resolves\neach name to a URL via `GET /v1/components` at startup and\ntries them in order on each turn, cascading to the next on\ntransport error / 5xx / timeout (but not on 4xx). At least\none entry is required. (Not a URL — a topology entry name.)\n',
        min_length=1,
    )


class BackendKind(StrEnum):
    """
    Which adapter the hemisphere-driver instance is configured to use.
    Reported by `/v1/info` so the orchestrator can log and the UI can
    render a label. `claude_code_cli` and `codex_cli` shell out to the
    respective CLIs (primary mode for personal installations).

    """

    anthropic_api = 'anthropic_api'
    openai_api = 'openai_api'
    claude_code_cli = 'claude_code_cli'
    codex_cli = 'codex_cli'
    openai_compat_http = 'openai_compat_http'


class Problem(BaseModel):
    """
    Error response shape, modeled on RFC 7807 (problem+json). Every
    Eugene Plexus component returns this for 4xx / 5xx responses.

    """

    type: str = Field(
        ...,
        description='A URI reference identifying the problem type, per RFC 7807.\nModeled as a plain string rather than `format: uri` to keep\nsentinel values like `about:blank` and ergonomic at call sites.\n',
    )
    title: str = Field(..., description='Short human-readable summary.')
    status: int = Field(..., description='HTTP status code.')
    detail: str | None = Field(
        None, description='Human-readable explanation specific to this occurrence.'
    )
    instance: str | None = Field(
        None,
        description='A URI reference identifying the specific occurrence. Modeled\nas a plain string for the same reason as `type`.\n',
    )
    component: str | None = Field(
        None,
        description='Eugene Plexus component name that originated the error\n(e.g. `"orchestrator"`, `"hemisphere-driver:left"`).\n',
    )


class Status(StrEnum):
    ok = 'ok'
    degraded = 'degraded'
    error = 'error'


class Health(BaseModel):
    """
    Liveness / readiness response shape.
    """

    status: Status
    version: str | None = Field(None, description='Component version (semver).')
    component: str | None = Field(
        None, description='Component identifier (e.g. `"hemisphere-driver"`).'
    )
    safeMode: bool | None = Field(
        False,
        description="True when the component was started with the watchdog's\nsafe-mode env var set\n(`EUGENE_PLEXUS_<KIND>_SAFE_MODE=1`) and is therefore\nrunning on built-in defaults instead of its persisted\nconfig. Components in safe mode are reachable for config\nediting (`PATCH /v1/config` writes to disk normally) but\nshould be considered non-functional for their primary\npurpose until restarted without the flag. `status` is\nalso reported as `degraded` while safe mode is in effect.\n",
    )
    details: dict[str, Any] | None = Field(
        None, description='Optional component-specific health detail.'
    )


class ConfigValueType(StrEnum):
    """
    The kind of value a config field holds. The UI uses this to pick
    a renderer (text input, dropdown, password field, etc.).

    """

    string = 'string'
    integer = 'integer'
    number = 'number'
    boolean = 'boolean'
    enum = 'enum'
    secret = 'secret'
    file_path = 'file_path'
    url = 'url'
    duration = 'duration'
    driver_list = 'driver_list'


class ConfigFieldShowWhen(BaseModel):
    """
    Predicate over another `ConfigField`'s current value. The UI
    renders the field this is attached to only when the named field
    equals the given value (or matches one entry in the given list).

    """

    key: str = Field(
        ...,
        description='`key` of another field in the same `ConfigSchema` to compare\nagainst.\n',
    )
    equals: Any = Field(
        ...,
        description="Value the named field must equal for this field to render.\nUntyped — when scalar, matches by literal equality against\nthe referenced field's `valueType`. When an array, matches\nif the referenced field's current value equals any entry\n(set-membership). Use the array form for a field that\napplies to multiple entries of an enum (e.g. an `apiKey`\nfield shared across several OpenAI-compatible providers).\n",
    )


class ConfigDocument(BaseModel):
    """
    Current effective config values, keyed by `ConfigField.key`.
    Values of fields with `sensitive: true` are returned as the
    literal string `"<redacted>"` regardless of whether they are
    set. Returned by `GET /v1/config`.

    """

    model_config = ConfigDict(
        extra='allow',
    )


class ConfigUpdateRequest(BaseModel):
    """
    Partial update for `PATCH /v1/config`. Every present key is
    set; absent keys are left unchanged. To revert a field to its
    default, send `null` as the value. Sensitive fields are written
    through directly (the redacted form sent back by GET is never
    accepted as a write value).

    """

    model_config = ConfigDict(
        extra='allow',
    )


class ConfigFieldError(BaseModel):
    """
    A per-field validation failure during PATCH.
    """

    key: str
    message: str


class ConfigUpdateResult(BaseModel):
    """
    Outcome of a `PATCH /v1/config` call. Validation failures on
    individual keys do not abort the whole request — valid changes
    are applied, invalid ones are reported in `rejected`.

    """

    applied: list[str] = Field(
        ..., description='Keys that were validated and applied successfully.'
    )
    rejected: list[ConfigFieldError] = Field(
        ...,
        description='Keys whose new values failed validation. The current value\nis preserved.\n',
    )
    requiresRestart: bool = Field(
        ...,
        description='True if any key in `applied` has `requiresRestart: true`,\nmeaning a process restart is needed for the change to take\neffect. The UI should surface this to the user.\n',
    )
    pendingRestart: list[str] | None = Field(
        None,
        description='Keys whose new values are stored but not yet active. Subset\nof `applied`. Empty unless `requiresRestart` is true.\n',
    )


class ConfigTestRequest(BaseModel):
    """
    Optional override for `POST /v1/config/test`. Same shape as
    `ConfigUpdateRequest`: keys override the saved config for the
    duration of the test only. Useful for "Test Connection" UIs where
    the operator wants to verify a new API key, URL, or model
    identifier before committing it. Send an empty body (`{}`) to
    test the saved config as-is.

    """

    overrides: ConfigUpdateRequest | None = None


class ConfigTestResult(BaseModel):
    """
    Result of a `POST /v1/config/test` invocation. Components decide
    what "test" means for their own surface: hemisphere-driver runs
    a minimal `generate()` round-trip; orchestrator probes its
    configured hemispheres + memory; memory verifies the store
    backend is reachable.

    """

    ok: bool = Field(
        ..., description='True iff the test invocation succeeded end-to-end.'
    )
    component: str = Field(
        ...,
        description='Component identifier (matches `ConfigSchema.component`).\nEchoed for UI clarity when several /v1/config/test responses\nland in the same view.\n',
    )
    latencyMs: int = Field(
        ..., description='Wall-clock time the test took, in milliseconds.'
    )
    summary: str | None = Field(
        None,
        description='One-line human-readable result summary. Always set when\n`ok` is true; may be set on failure to add context beyond\n`error`.\n',
    )
    sampleOutput: str | None = Field(
        None,
        description="Brief sample of the data the test produced — e.g. assistant\ntext from a hemisphere-driver `generate()` round-trip. May be\ntruncated to keep the response small. Omitted when there's\nnothing useful to show.\n",
    )
    error: str | None = Field(
        None,
        description='Human-readable error message. Set when `ok` is false. Should\nbe specific enough that the operator can act on it (e.g.\n`"openaiApiKey rejected: 401 Unauthorized"`).\n',
    )


class SecurityMode(StrEnum):
    """
    Operator's choice for how the watchdog handles its master key
    between restarts. Set during the wizard's security screen; can
    be changed later from the Config page.

    * `prompt_on_startup` — passphrase required at every watchdog
      start. Master key lives only in process memory. Best for
      shared environments, sensitive conversations, security-
      conscious operators. A power outage means Eugene stays
      offline until the operator re-enters the passphrase.
    * `os_keyring` — master key stored in the OS secret store
      (Windows Credential Manager / macOS Keychain / Linux Secret
      Service via the `keyring` Python lib). OS unlocks tied to
      user login; Eugene auto-recovers from restarts. Best for
      home / personal-use installs and anyone who wants minimum
      friction. Anyone with the OS account can also start Eugene.

    """

    prompt_on_startup = 'prompt_on_startup'
    os_keyring = 'os_keyring'


class AuthLoginRequest(BaseModel):
    """
    Login request body sent by the UI to `POST /v1/auth/login` on
    the watchdog. The passphrase is the same one the operator set
    in the wizard. The watchdog bcrypt-compares it; on match,
    issues a session token.

    """

    passphrase: str = Field(..., min_length=1)


class AuthLoginResponse(BaseModel):
    """
    Issued on successful login. The UI stores `sessionToken` as a
    Secure / HttpOnly / SameSite=Strict cookie or in memory; every
    subsequent proxy request includes it as
    `Authorization: Bearer <token>`.

    """

    sessionToken: str = Field(
        ...,
        description='Opaque bearer token. Signed and validated server-side; the\nUI should never inspect its contents. Lifetime is bounded\nby `expiresAt`.\n',
    )
    expiresAt: AwareDatetime
    operatorName: str | None = Field(
        None,
        description='The operator\'s display name from the constitution\n(typically "operator" or whatever the operator set).\nEchoed for UI welcome strings.\n',
    )


class Alg(StrEnum):
    """
    Encryption algorithm identifier.
    """

    secretbox_xsalsa20poly1305 = 'secretbox-xsalsa20poly1305'


class MasterKeyEnvelope(BaseModel):
    """
    Encrypted-at-rest envelope for sensitive config fields. The
    on-disk YAML for fields marked `sensitive: true` is stored as
    this envelope when v0.2 security is enabled; the component
    decrypts using the master key passed in by the watchdog at
    spawn time (env var `EUGENE_PLEXUS_<KIND>_MASTER_KEY`,
    base64-encoded).

    Algorithm: libsodium secretbox (XSalsa20-Poly1305). The nonce
    is generated per-encryption and stored alongside the
    ciphertext. The master key is 32 bytes derived from the
    operator's passphrase via Argon2id with parameters chosen at
    first-run time and persisted in the watchdog's state.

    Components MAY accept plaintext values in PATCH requests
    (current behavior); on persist, they encrypt to this envelope
    if the master key is available. GET requests continue to
    return `"<redacted>"` for sensitive fields regardless of
    envelope-vs-plaintext on disk.

    """

    alg: Alg = Field(..., description='Encryption algorithm identifier.')
    nonce: str = Field(
        ...,
        description='Base64-encoded 24-byte nonce. Generated per-encryption,\nnever reused with the same key.\n',
    )
    ciphertext: str = Field(..., description='Base64-encoded ciphertext + auth tag.')


class PersonRef(BaseModel):
    """
    Reference to a person Eugene knows. The `personId` is the
    identity component's stable key (UUID). Each person has zero
    or more platform aliases linking external IDs back to this
    person; the operator approves aliasing via the pending-links
    flow.

    v0.2 distinguishes between the operator (always known, defined
    by the wizard) and other persons (introduced via connector
    adapters). The operator's `personId` is special-cased in some
    endpoints — e.g. the UI's chat surface always sends as the
    operator.

    """

    personId: UUID
    displayName: str | None = Field(
        None, description='Operator-supplied or auto-from-platform display name.'
    )
    isOperator: bool | None = Field(
        False, description="True iff this person is the install's operator."
    )


class PlatformAlias(BaseModel):
    """
    One external-platform identity that maps to a person. The
    union of (platform, accountId) is globally unique. Created
    when the operator approves a pending identity link.

    """

    platform: str = Field(
        ...,
        description='Platform identifier (e.g. `"discord"`, `"slack"`,\n`"matrix"`, `"ui"`). The `ui` platform is reserved for\nthe local UI session; the operator is always\n`(platform=ui, accountId=operator)`.\n',
    )
    accountId: str = Field(
        ...,
        description="Platform-stable account identifier (Discord user ID,\nMatrix MXID, Slack member ID, etc.). MUST be the\nplatform's immutable id, not a mutable handle.\n",
    )
    handle: str | None = Field(
        None, description='Username / handle on the platform (mutable).'
    )
    displayName: str | None = Field(
        None, description='Platform display name (mutable).'
    )
    avatarUrl: AnyUrl | None = Field(
        None, description='Avatar image URL on the platform.'
    )
    linkedAt: AwareDatetime


class Status1(StrEnum):
    pending = 'pending'
    approved = 'approved'
    rejected = 'rejected'


class PendingIdentityLink(BaseModel):
    """
    An unknown identity that wants to interact with Eugene. The
    connector adapter creates these when a new platform user
    @mentions Eugene or DMs for the first time. The operator
    approves or rejects from the UI; until then the identity has
    no relationship context and Eugene treats it as a stranger.

    Universal fields only — every plausible future platform
    (Slack, Matrix, Telegram, Gmail, Signal) supplies these.
    Platform-specific extras live in `adapterPrivate` and are
    NOT promoted to the operator-facing UI unless the operator
    drills in.

    """

    linkId: UUID
    platform: str
    accountId: str
    displayName: str | None = None
    handle: str | None = None
    avatarUrl: AnyUrl | None = None
    firstSeen: AwareDatetime
    triggeringMessage: str = Field(
        ...,
        description='The text of the message that triggered the link request,\ntruncated. Gives the operator context for the approval\ndecision.\n',
    )
    status: Status1
    adapterPrivate: dict[str, Any] | None = Field(
        None,
        description='Platform-specific metadata the adapter stored alongside\nthis link. UI may render this in a drill-down view but\ndoes not promote it to the main approval surface. Use\nfor things like Teams UPN/tenant, Slack workspace,\nMatrix homeserver.\n',
    )


class LinkApprovalRequest(BaseModel):
    """
    Operator action on a pending identity link. To link the
    unknown identity to an existing person (typically the
    operator themselves or a known third party), supply
    `linkAsPersonId`. To create a new person record for this
    identity, omit `linkAsPersonId` and supply `displayName`
    and optionally `relationshipNote`.

    """

    linkAsPersonId: UUID | None = Field(
        None,
        description='Existing person to alias this identity onto. Mutually\nexclusive with `displayName` / `relationshipNote`.\n',
    )
    displayName: str | None = Field(
        None,
        description='Display name for the new person record. Required when\n`linkAsPersonId` is omitted.\n',
    )
    relationshipNote: str | None = Field(
        None,
        description='Optional initial relationship context for the new person\n(e.g. "my wife", "Discord regular"). Only used when\n`linkAsPersonId` is omitted.\n',
    )


class Constitution(BaseModel):
    """
    The immutable / declarative half of Eugene's identity — the
    "I am Eugene" facts. Operator-editable from the UI; Eugene
    cannot modify this. Anatomically: medial prefrontal cortex
    (mPFC) node of the Default Mode Network.

    v0.2 reserves three structured keys (`name`, `pronouns`,
    `coreValues`) that the orchestrator reads programmatically
    when constructing hemisphere prompts. The `freeText` field is
    operator-owned free-form context (markdown / YAML / plain)
    that's included verbatim in every prompt. Future versions
    may promote stable patterns out of `freeText` into structured
    fields, but the operator-flexibility-first design choice was
    deliberate (we can't enumerate all immutable identity data
    yet).

    """

    name: str = Field(
        ...,
        description="Eugene's name. Operator may rename (e.g. if they want\ntheir consciousness called something else). Used in\nevery hemisphere system prompt and in UI chrome.\n",
        min_length=1,
    )
    pronouns: str | None = Field(
        None,
        description='Eugene\'s pronouns (e.g. "he/him", "they/them"). Used\nin hemisphere prompts for self-reference consistency.\n',
    )
    coreValues: list[str] | None = Field(
        None,
        description='Short list of operator-supplied core values. Each is a\nshort phrase ("honesty", "intellectual humility",\n"patience with confusion"). Included in every\nhemisphere prompt.\n',
    )
    freeText: str | None = Field(
        None,
        description="Operator-owned free-form context — markdown or plain\ntext. Included verbatim in every hemisphere prompt\nafter the structured fields. Use for backstory, voice\nguidance, anything that doesn't fit a structured field\nyet.\n",
    )


class SelfModelEntry(BaseModel):
    """
    One entry in Eugene's self-model — the autobiographical
    / mutable half of identity. Anatomically: posterior cingulate
    cortex (PCC) / precuneus node of the Default Mode Network.

    Self-model entries are written by Eugene's reflection process
    (v0.2: manually triggered via `POST /v1/identity/self-model/reflect`;
    v0.3: autonomous when NT state is in reflection mode).
    They're queried by topic relevance and injected into
    hemisphere prompts when relevant.

    """

    id: UUID
    topic: str = Field(
        ...,
        description='Short topic key for retrieval (e.g. "creative-tasks",\n"user-troy", "uncertainty-handling").\n',
    )
    content: str = Field(
        ...,
        description="The reflection itself. Free-form prose written by\nEugene's reflection process. Typically 1-3 sentences.\n",
    )
    relatedPersonIds: list[UUID] | None = Field(
        None, description='Persons this reflection involves, if any.\n'
    )
    createdAt: AwareDatetime
    sourceConversationIds: list[UUID] | None = Field(
        None,
        description='Conversation ids that fed into this reflection. Lets the\nUI offer "show me the conversations that produced this\nself-model entry" drill-down.\n',
    )


class MemoryBackendKind(StrEnum):
    """
    Which storage backend the memory component is using. Set in
    the memory component's config. v0.2 ships one option; future
    versions add adapters following the same pattern as
    `hemisphere-driver`'s provider registry.

    """

    local_sqlite = 'local_sqlite'


class MemoryEmbeddingSource(StrEnum):
    """
    How the memory component generates embeddings for similarity
    search. `local` uses sentence-transformers (offline, ~100MB
    model download on first install). `api` calls a vendor
    (OpenAI / Voyage / Cohere) and requires network + an API
    key. Lives inside `local_sqlite`'s adapter-specific config.

    """

    local = 'local'
    api = 'api'


class MemorySearchRequest(BaseModel):
    """
    Reactive memory search. Called by the orchestrator when its
    topic-shift detector (v0.3) flags that the current
    conversation references something outside recent history,
    or when the operator explicitly requests retrieval. v0.2
    ships the endpoint; the trigger is v0.3.

    """

    query: str = Field(..., description='Free-form query text to embed and search.')
    personId: UUID | None = Field(
        None,
        description='Optionally restrict search to entries involving this\nperson.\n',
    )
    conversationId: UUID | None = Field(
        None, description='Optionally restrict search to a specific conversation.\n'
    )
    limit: int | None = Field(10, ge=1, le=100)
    minScore: float | None = Field(
        None,
        description='Minimum similarity score to include. Backends define\ntheir own scoring scale; 0.5 is a reasonable default\nfor cosine-similarity embedding backends.\n',
        ge=0.0,
        le=1.0,
    )


class AdapterKind(StrEnum):
    """
    Which external platform adapter is configured. v0.2 ships
    one; later versions add slack, matrix, telegram, gmail, etc.

    """

    discord = 'discord'


class AdapterEntry(BaseModel):
    """
    One configured platform adapter inside the connector. Like
    hemisphere-driver's `drivers` config but for outbound
    platforms. Each entry runs its own adapter loop (Discord
    Gateway WS connection, Slack RTM, etc.) and bridges
    incoming/outgoing messages between the platform and the
    orchestrator.

    """

    name: str = Field(
        ...,
        description='Operator-supplied label (e.g. `"work-discord"`,\n`"family-slack"`). Used in logs and the UI.\n',
        min_length=1,
    )
    kind: AdapterKind
    adapterConfig: dict[str, Any] | None = Field(
        None,
        description="Adapter-specific config (bot token, channel allowlist,\netc.). Schema is adapter-defined; the connector's\n`GET /v1/adapters/{name}/config/schema` returns the\nschema for the current adapter so the UI can render\nan editor.\n",
    )
    enabled: bool | None = True


class MessageSource(BaseModel):
    """
    Where a message came from. Lets the orchestrator and UI
    distinguish "operator typing in the local UI" from
    "Discord channel mention" without needing
    adapter-specific code paths.

    """

    platform: str = Field(
        ...,
        description='Same identifiers used in `PlatformAlias.platform`\n(`"ui"`, `"discord"`, etc.).\n',
    )
    channelId: str | None = Field(
        None,
        description="Platform channel identifier (Discord channel id,\nSlack channel id, Matrix room id, etc.). Omitted for\nDMs or where the platform doesn't expose channels.\n",
    )
    channelName: str | None = Field(
        None, description='Human-readable channel name (mutable).'
    )
    isDirectMessage: bool | None = False


class ChannelContextEntry(BaseModel):
    """
    One message from the channel that precedes Eugene's
    invocation. Used by adapters to provide grounding context
    for channel mentions. Not persisted to memory.

    """

    author: str = Field(
        ...,
        description="Platform display name of the speaker. Free-form;\nEugene doesn't try to resolve to known persons (would\nrequire trust-establishing flows that v0.2 doesn't\nhave for non-mention authors).\n",
    )
    content: str
    timestamp: AwareDatetime


class RestartResult(BaseModel):
    """
    Acknowledgement returned by `POST /v1/admin/restart`. The
    component schedules its own process exit shortly after returning
    this response (typically a few hundred ms — long enough for the
    HTTP response to flush). The component does NOT bring itself
    back up; a process supervisor (systemd, docker-compose, the
    deploy launcher, etc.) is expected to relaunch it. In v0.1
    personal-use deploys without a supervisor, the operator
    relaunches manually.

    """

    scheduled: bool = Field(
        ...,
        description='True if the component accepted the restart and an exit is\nqueued. Always true in v0.1 — the endpoint has no reason to\nrefuse — but typed as a boolean so future versions can gate\non (e.g.) an in-flight long-running operation.\n',
    )
    delayMs: int = Field(
        ...,
        description='How long the component intends to wait before calling exit,\nmeasured from the moment the response is sent. Lets clients\ntime their UI ("restarting in 0.5s…") and decide when to\nstart polling `/healthz` for the relaunched process.\n',
        ge=0,
    )
    message: str | None = Field(
        None,
        description='Optional human-readable note (e.g. "logs flushed, exiting\nnow"). UI may display this in the restart-progress dialog.\n',
    )


class TrainingGoal(StrEnum):
    """
    Mirrors the wizard's "what do you want to do" screen. Drives which
    recipe/fields the UI surfaces (via showWhen) and which defaults apply.

    """

    pretrain_from_scratch = 'pretrain_from_scratch'
    continue_pretraining = 'continue_pretraining'
    finetune = 'finetune'
    train_adapter = 'train_adapter'
    evaluate = 'evaluate'
    serve = 'serve'


class ModelType(StrEnum):
    decoder_only = 'decoder_only'


class Activation(StrEnum):
    relu = 'relu'
    leaky_relu = 'leaky_relu'
    gelu = 'gelu'
    elu = 'elu'
    swiglu = 'swiglu'


class AttentionVariant(StrEnum):
    gqa = 'gqa'
    differential = 'differential'


class Type(StrEnum):
    dense = 'dense'
    moe = 'moe'


class Ffn(BaseModel):
    """
    Replaces CLLM's cognitive/hemisphere FFN with a generic dense|moe choice.
    """

    type: Type | None = 'dense'
    nExperts: int | None = Field(None, ge=1)
    topK: int | None = Field(None, ge=1)
    useSharedExpert: bool | None = False
    auxLossWeight: float | None = None


class MixtureOfDepths(BaseModel):
    enabled: bool | None = False
    capacityFactor: float | None = None
    auxLossWeight: float | None = None


class Mode(StrEnum):
    none = 'none'
    ntk = 'ntk'
    yarn = 'yarn'


class ContextExtension(BaseModel):
    mode: Mode | None = 'none'
    maxFactor: float | None = None


class ArchitectureConfig(BaseModel):
    """
    Generic decoder-only transformer config. Lifted from CLLM's
    architecture package with all NT/hemisphere/cognitive fields removed.
    See §10: cognitive.use_moe -> generic ffn.type; mood_vector dropped.

    """

    modelType: ModelType
    nLayer: int = Field(..., ge=1)
    nHead: int = Field(..., ge=1)
    nKvHead: int | None = Field(None, description='GQA KV heads; omit for full MHA.')
    nEmbd: int = Field(..., description='Must be divisible by nHead.', ge=1)
    blockSize: int = Field(..., description='Training context length.', ge=1)
    vocabSize: int = Field(..., ge=1)
    activation: Activation | None = 'swiglu'
    ropeBase: float | None = 500000
    useQkNorm: bool | None = False
    attentionVariant: AttentionVariant | None = 'gqa'
    ffn: Ffn | None = Field(
        None,
        description="Replaces CLLM's cognitive/hemisphere FFN with a generic dense|moe choice.",
    )
    mixtureOfDepths: MixtureOfDepths | None = None
    blockAttnResGroupSize: int | None = Field(0, description='0 = disabled.')
    contextExtension: ContextExtension | None = None
    weightTying: bool | None = True


class Kind(StrEnum):
    pretraining = 'pretraining'
    continued_pretraining = 'continued_pretraining'
    sft = 'sft'
    lora = 'lora'
    qlora = 'qlora'
    dpo = 'dpo'


class Adapter(BaseModel):
    """
    LoRA/QLoRA adapter config (kind in [lora, qlora]).
    """

    rank: int | None = Field(None, ge=1)
    alpha: float | None = None
    dropout: float | None = None
    targetModules: list[str] | None = None


class Bits(IntEnum):
    integer_4 = 4
    integer_8 = 8


class ComputeDtype(StrEnum):
    bf16 = 'bf16'
    fp16 = 'fp16'


class Quantization(BaseModel):
    """
    QLoRA base-weight quantization (kind == qlora).
    """

    bits: Bits | None = None
    computeDtype: ComputeDtype | None = None


class Kind1(StrEnum):
    adamw = 'adamw'
    sgd = 'sgd'
    adadelta = 'adadelta'
    adabelief = 'adabelief'
    muon = 'muon'


class Optimizer(BaseModel):
    kind: Kind1
    learningRate: float
    weightDecay: float | None = None
    betas: list[float] | None = Field(None, max_length=2, min_length=2)
    eps: float | None = None
    fused: bool | None = True


class Kind2(StrEnum):
    wsd = 'wsd'
    epoch = 'epoch'
    plateau = 'plateau'
    cosine = 'cosine'


class DecayType(StrEnum):
    cosine = 'cosine'
    linear = 'linear'


class Scheduler(BaseModel):
    kind: Kind2 | None = 'wsd'
    warmupSteps: int | None = None
    maxLr: float | None = None
    minLr: float | None = None
    totalSteps: int | None = Field(None, description='Omit to derive via chinchilla.')
    chinchillaTokensPerParam: float | None = Field(
        None, description='Auto total_steps when totalSteps null.'
    )
    decayType: DecayType | None = None
    decayFraction: float | None = None


class Dtype(StrEnum):
    auto = 'auto'
    bf16 = 'bf16'
    fp16 = 'fp16'
    fp32 = 'fp32'


class GradScaler(StrEnum):
    auto = 'auto'
    always = 'always'
    never = 'never'


class Precision(BaseModel):
    dtype: Dtype | None = 'auto'
    gradScaler: GradScaler | None = 'auto'


class GradientClip(BaseModel):
    percentile: float | None = 0.9
    historySize: int | None = 100
    maxClipValue: float | None = None
    minClipValue: float | None = None


class CollapseStop(BaseModel):
    """
    Mode-collapse early stop (CLLM SampledTokenTracker, de-consciousness'd).
    """

    minLogitEntropy: float | None = None
    warmupGraceSteps: int | None = None


class Hyperparameters(BaseModel):
    """
    Every output-affecting knob, grouped. Sourced from CLLM's training config.
    """

    batchSize: int | None = Field(None, ge=1)
    gradAccumSteps: int | None = Field(1, ge=1)
    maxSteps: int | None = Field(
        None, description='Omit to derive from maxEpochs / dataset size.'
    )
    maxEpochs: int | None = None
    seed: int | None = 1337
    optimizer: Optimizer | None = None
    scheduler: Scheduler | None = None
    precision: Precision | None = None
    gradientClip: GradientClip | None = None
    collapseStop: CollapseStop | None = Field(
        None,
        description="Mode-collapse early stop (CLLM SampledTokenTracker, de-consciousness'd).",
    )


class Mode1(StrEnum):
    cpu = 'cpu'
    single_gpu = 'single_gpu'
    multi_gpu = 'multi_gpu'
    multi_node = 'multi_node'


class Backend(StrEnum):
    nccl = 'nccl'
    gloo = 'gloo'


class Node(BaseModel):
    host: str | None = None
    gpuCount: int | None = None
    nodeRank: int | None = None


class CheckpointStrategy(StrEnum):
    master_only = 'master_only'
    all_nodes = 'all_nodes'


class Distributed(BaseModel):
    """
    Present for multi_gpu / multi_node.
    """

    backend: Backend | None = 'nccl'
    masterAddr: str | None = None
    masterPort: int | None = None
    nodes: list[Node] | None = None
    findUnusedParameters: bool | None = False
    bucketCapMb: int | None = None
    gradientAsBucketView: bool | None = None
    staticGraph: bool | None = None
    checkpointStrategy: CheckpointStrategy | None = 'master_only'


class HardwareTopology(BaseModel):
    """
    How a run is placed on hardware. Sourced from CLLM gpu_manager +
    distributed_config (torchrun/DDP env generation).

    """

    mode: Mode1
    gpuIndices: list[int] | None = None
    excludeGpus: list[int] | None = None
    minMemoryGb: float | None = None
    distributed: Distributed | None = Field(
        None, description='Present for multi_gpu / multi_node.'
    )


class RunStatus(StrEnum):
    """
    queued -> preparing (build model/data/optimizer) -> running -> completed.
    paused/resumed are operator actions; failed carries lastError; cancelled
    is operator-initiated stop. Note: these are RUN states owned by the
    trainer service, distinct from the watchdog's ComponentStatus for the
    trainer PROCESS.

    """

    queued = 'queued'
    preparing = 'preparing'
    running = 'running'
    paused = 'paused'
    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'


class TrainingMetricPoint(BaseModel):
    """
    One sampled point of training health. Streamed over SSE + persisted for curves.
    """

    step: int = Field(..., ge=0)
    timestamp: AwareDatetime | None = None
    loss: float | None = None
    valLoss: float | None = None
    learningRate: float | None = None
    gradNorm: float | None = None
    gradClipValue: float | None = None
    tokensPerSec: float | None = None
    vramGb: float | None = None
    tokenEntropy: float | None = Field(
        None, description='Sampled-token Shannon entropy (collapse monitor).'
    )


class Checkpoint(BaseModel):
    """
    A saved model state produced by a run. Consumed by eval + inference.
    """

    checkpointId: UUID
    runId: UUID
    projectId: UUID | None = None
    step: int = Field(..., ge=0)
    epoch: int | None = Field(None, ge=0)
    createdAt: AwareDatetime
    path: str | None = Field(None, description='Filesystem path on the trainer host.')
    sizeBytes: int | None = None
    valLoss: float | None = None
    isLatest: bool | None = False
    isBest: bool | None = False
    tags: list[str] | None = None


class CheckpointRef(BaseModel):
    """
    Lightweight reference to a checkpoint (id + enough to display).
    """

    checkpointId: UUID
    runId: UUID | None = None
    step: int | None = None
    label: str | None = None


class DatasetRef(BaseModel):
    """
    Reference to a dataset MANIFEST owned by the data component, plus the
    per-project curriculum settings (weight + min-iteration gate) sourced
    from CLLM's datasets.json schema.

    """

    datasetId: UUID
    name: str | None = None
    samplingWeight: float | None = Field(
        1, description='Oversample(>1)/subsample(<1) factor.'
    )
    minIteration: int | None = Field(
        0, description='Curriculum gate; introduce at this step.'
    )


class TokenizerRef(BaseModel):
    """
    Reference to a tokenizer owned by the data component (+ its vocab fingerprint).
    """

    tokenizerId: UUID
    name: str | None = None
    vocabSize: int | None = None
    vocabFingerprint: str | None = Field(
        None, description='SHA256; must match dataset pretokenization.'
    )


class EvalSuiteRef(BaseModel):
    evalSuiteId: UUID
    name: str | None = None


class Format(StrEnum):
    native = 'native'
    safetensors = 'safetensors'
    gguf = 'gguf'


class ExportSettings(BaseModel):
    """
    How/where a finished model is served. Points at the inference component.
    """

    autoServeOnComplete: bool | None = False
    target: str | None = Field(
        None,
        description='Inference endpoint name. Rendered as a componentKindHint dropdown\n(kind: inference) in the UI; saved value is the peer URL.\n',
    )
    format: Format | None = 'native'


class Kind3(StrEnum):
    data_prep = 'data_prep'
    tokenizer = 'tokenizer'
    training = 'training'
    eval = 'eval'
    serve = 'serve'


class PipelineStatus(StrEnum):
    """
    Per-stage and overall status. skipped = stage not requested for this project.
    """

    pending = 'pending'
    running = 'running'
    paused = 'paused'
    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'
    skipped = 'skipped'


class SpawnConfig(BaseModel):
    configFile: str = Field(
        ...,
        description="Absolute path to the component's own config file. The\nwatchdog passes this to the component via its\nkind-specific env var\n(`EUGENE_PLEXUS_<KIND>_CONFIG_FILE`) at spawn time.\n",
    )
    env: dict[str, str] | None = Field(
        None,
        description='Optional extra environment variables to pass to the\nspawned process. Reserved for advanced operators; the\nwizard never sets this.\n',
    )


class ComponentStatus(StrEnum):
    """
    Current operational state.

    * `starting` — watchdog has spawned the process but it has
      not yet answered `/healthz`.
    * `running` — process is up and `/healthz` is healthy.
    * `safe_mode` — process is up but launched with
      `SAFE_MODE=1`; will refuse to do useful work until the
      operator fixes its config and clears the safe-mode flag.
    * `exited` — process exited cleanly and the watchdog is in
      the middle of respawning it (transient state).
    * `crashed` — process has exited non-zero repeatedly and the
      watchdog has given up auto-restarting it. Operator must
      restart it manually after fixing the cause.
    * `unreachable` — for remote components, the watchdog can't
      reach the URL. For spawned components this state is not
      used (use `crashed` or `exited` instead).

    """

    starting = 'starting'
    running = 'running'
    safe_mode = 'safe_mode'
    exited = 'exited'
    crashed = 'crashed'
    unreachable = 'unreachable'


class Component(BaseModel):
    """
    Combined declarative + operational view of one supervised
    component. The declarative half (`name`, `kind`, `url`,
    `spawn`, `safeMode`) is what's persisted to `watchdog.yaml`.
    The operational half (`status`, `lastRestart`, `lastError`,
    `pid`) is observed at runtime and not persisted.

    """

    name: str = Field(
        ...,
        description="Operator-supplied label, also used in the orchestrator's `drivers` list.",
    )
    kind: ComponentKind
    url: AnyUrl = Field(
        ...,
        description='Canonical address. For spawned components the watchdog\nparses the port out of this URL and passes it via env var\n(`EUGENE_PLEXUS_<KIND>_BIND_PORT`); for remote components\nthis is what the watchdog probes.\n',
    )
    spawn: SpawnConfig | None = Field(
        None,
        description="Present iff this component runs locally under watchdog\nsupervision. Absence means it's remote (the watchdog only\nmonitors reachability).\n",
    )
    safeMode: bool | None = Field(
        False,
        description='When true the watchdog launches the spawned component with\n`EUGENE_PLEXUS_<KIND>_SAFE_MODE=1`, telling it to ignore its\nown config file and boot from defaults. Used to recover\nfrom a config that breaks startup. Ignored for remote\ncomponents.\n',
    )
    status: ComponentStatus
    pid: int | None = Field(
        None,
        description='Operating-system process id. Set only for spawned, currently-running components.',
    )
    lastRestart: AwareDatetime | None = Field(
        None, description='When the watchdog last started or restarted this component.'
    )
    lastError: str | None = Field(
        None,
        description="Most recent error observed for this component. Reset to null\non successful restart. Useful for surfacing why a component\nkeeps crashing in the UI's Components tab.\n",
    )


class NTState(BaseModel):
    """
    A snapshot of Eugene's neurotransmitter state. v0.2 introduces real
    modulation: the orchestrator updates this from observations each
    chat turn, and the bicameral loop reads it to set `max_passes`,
    `temperature`, and blend weights. CLLM-inspired anxiety-driven
    termination is the load-bearing behavior.

    Six NTs in v0.2 (cortisol replaces v0.1's glutamate — cortisol is
    directly observable from chat patterns like sustained divergence
    and time pressure; glutamate's lower-level activation modeling
    waits for v0.3). All values in [0, 1]; `level` carries the current
    instantaneous value, `baseline` the resting state the field decays
    toward, `decay` the per-second decay rate.

    v0.3+ adds: full 12-NT shape (oxytocin, endorphins, melatonin,
    adenosine, histamine, orexin), per-driver NT modulation, drives
    feeding NT, NT-driven autonomous-thinking triggers.

    """

    lastUpdated: AwareDatetime = Field(
        ...,
        description='When NT levels were last updated. Used by the orchestrator\nto compute elapsed-time decay on the next tick.\n',
    )
    dopamine: NTLevel
    serotonin: NTLevel
    norepinephrine: NTLevel
    gaba: NTLevel
    cortisol: NTLevel
    acetylcholine: NTLevel


class ConfigField(BaseModel):
    """
    UI-renderable description of a single editable config field.

    """

    key: str = Field(
        ...,
        description='Stable machine-readable id, dot-separated for grouping\n(e.g. `"adapter.modelId"`).\n',
    )
    label: str = Field(..., description='Human-readable label for the UI.')
    description: str | None = Field(
        None, description='One-sentence explanation suitable for non-programmers.'
    )
    category: str = Field(
        ...,
        description='Group key for UI tabbing or sectioning (e.g. `"adapter"`,\n`"logging"`, `"network"`). Mapped to a display label via\n`ConfigSchema.categories`.\n',
    )
    valueType: ConfigValueType
    default: Any | None = Field(
        None,
        description='Default value if unset. Type matches `valueType`. Omitted\nfor fields with no default.\n',
    )
    enumValues: list[str] | None = Field(
        None, description='Allowed values when `valueType == enum`.'
    )
    suggestions: list[str] | None = Field(
        None,
        description="Discovery-time hints — values the operator might want\nbut which AREN'T enforced by validation. UIs render\nstring-typed fields with non-empty `suggestions` as a\ncombobox (free-text input with a dropdown of suggestions)\nrather than a strict dropdown. Use when the set of\nvalid values is large, partially-discoverable, or\nextends beyond what the component knows at the moment\n(e.g. local LLM model lists that update when the operator\npulls a new model). Distinct from `enumValues`:\nsuggestions are advisory, enumValues are mandatory.\n",
    )
    componentKindHint: ComponentKind | None = Field(
        None,
        description="Declarative rendering hint: this field references a peer\ncomponent of the given kind. UIs render any kind-hinted\nfield as a dropdown sourced from the watchdog's\n`/v1/components` (filtered by kind), with `(off)` as the\nfirst option (saves an empty string). For single-instance\nkinds (memory, identity, etc.) the dropdown UX collapses\nto effectively a toggle; for multi-instance kinds\n(hemisphere-driver) the operator picks one. Pairs with a\nstring/url `valueType` — the saved value is still the\npeer's URL, the hint only changes how the UI looks it up.\nAvoids the OpenClaw trap of duplicating topology into\nfree-text URL fields the operator has to type by hand.\n",
    )
    enumLabels: list[str] | None = Field(
        None,
        description='Optional human-readable display labels paired one-to-one\nwith `enumValues`. UIs that render an enum as a dropdown\nshould show `enumLabels[i]` while still submitting\n`enumValues[i]` as the saved value. When omitted (or\nshorter than `enumValues`), UIs fall back to the raw\nvalue as the label. Useful where the stored key is\nmachine-friendly but the user-facing label isn\'t —\ne.g. `claude_subscription` saved, "Claude (Pro/Max)"\nshown.\n',
    )
    sensitive: bool | None = Field(
        False,
        description='If true, the value is redacted (`"<redacted>"`) in\n`ConfigDocument` responses but is accepted in\n`ConfigUpdateRequest`. Use for API keys, passwords, etc.\n',
    )
    required: bool | None = Field(
        False,
        description='If true, the component will refuse to start without this\nfield set (either in config or via env var fallback).\n',
    )
    minimum: float | None = Field(
        None, description='Validation hint for `integer` / `number` fields.'
    )
    maximum: float | None = Field(
        None, description='Validation hint for `integer` / `number` fields.'
    )
    pattern: str | None = Field(
        None, description='Regex validation hint for `string` / `url` / `file_path`.'
    )
    requiresRestart: bool | None = Field(
        False,
        description='If true, changes to this field via PATCH are accepted and\nstored but do not take effect until the component process\nrestarts. The UI should warn before submitting.\n',
    )
    showWhen: ConfigFieldShowWhen | None = Field(
        None,
        description="Conditional-rendering hint. When set, the UI should only\nrender this field when another field's current value matches\nthe condition. Used to hide adapter-specific fields\n(e.g. `openaiApiKey`) when a different adapter is selected.\nThe component still validates and stores the field\nregardless of UI visibility.\n",
    )


class ConfigSchema(BaseModel):
    """
    UI-renderable description of every editable config field this
    component accepts. Returned by `GET /v1/config/schema`. UIs use
    this to render a generic config editor without component-specific
    code.

    """

    component: str = Field(
        ..., description='Component identifier (e.g. `"hemisphere-driver"`).'
    )
    fields: list[ConfigField]
    categories: dict[str, str] | None = Field(
        None,
        description='Map from category key (used in `ConfigField.category`) to\na human-readable section label. Optional; UIs may fall back\nto the raw key.\n',
    )


class Person(BaseModel):
    """
    Full record of a known person. The identity component owns
    these. `aliases` lists all platform identities that have been
    approved as belonging to this person. The relationship summary
    is rebuilt on-demand by the memory component from raw turns
    in v0.2; v0.3 adds reactive synthesis via the topic-shift
    detector.

    """

    personId: UUID
    displayName: str
    isOperator: bool | None = False
    createdAt: AwareDatetime
    aliases: list[PlatformAlias] | None = None
    relationshipNote: str | None = Field(
        None,
        description='Optional free-form operator-supplied note about who this\nperson is to Eugene (e.g. "my wife", "the dev-banter\nchannel regular"). Surfaced into hemisphere prompts as\ntop-level relationship context.\n',
    )


class MemoryEntry(BaseModel):
    """
    One stored message + the cognitive metadata it was produced
    with. Memory writes typically happen at the end of each
    bicameral turn: the user's message and Eugene's final
    response each become entries. Hemisphere intermediate
    outputs are NOT persisted by default — they're debug
    artifacts.

    """

    entryId: UUID
    personId: UUID = Field(
        ...,
        description="The person this entry is *with* (the user side of the\nexchange, even for Eugene's responses — they're\nresponses to that person).\n",
    )
    conversationId: UUID
    role: Role
    content: str
    timestamp: AwareDatetime
    ntStateSnapshot: NTState | None = Field(
        None,
        description="Eugene's NT state at the time this entry was produced.\nLets later analysis correlate output style with NT\nstate. Optional — not all entries carry one.\n",
    )
    hemisphereAttribution: str | None = Field(
        None,
        description='For Eugene\'s responses: which hemisphere(s) produced\nthis. Free-form (e.g. "left-only", "blended", or a\ndriver name). Omitted for user messages.\n',
    )


class MemorySearchHit(BaseModel):
    entry: MemoryEntry
    score: float = Field(
        ...,
        description="Backend-defined similarity score. Higher = more\nrelevant. Scale depends on the backend; for\n`local_sqlite` it's cosine similarity in [0, 1].\n",
    )


class RelationshipSummary(BaseModel):
    """
    Per-person context the orchestrator injects into hemisphere
    prompts so Eugene speaks differently to different people.
    v0.2: built on-demand from raw recent turns with this person
    (skip-extraction approach). v0.3: synthesized via reactive
    memory extraction.

    """

    personId: UUID
    summary: str | None = Field(
        None,
        description='Short paragraph Eugene\'s hemispheres see before each\nturn (e.g. "Sarah is your wife. You talk about 3\ntimes a day, mostly casual, frequent jokes. She works\nin product."). Omitted when there\'s no synthesized\nsummary; the orchestrator will then build context\nfrom raw recent turns.\n',
    )
    turnCount: int | None = Field(
        None,
        description='How many turns Eugene has shared with this person.\nSurfaced in UI to give the operator a sense of how\nwell Eugene knows them.\n',
        ge=0,
    )
    lastUpdated: AwareDatetime
    recentTurns: list[MemoryEntry] | None = Field(
        None,
        description="Raw recent turns with this person, included alongside\n(or instead of) the synthesized summary. v0.2's\ndefault mode is recentTurns-only; v0.3 fills in\n`summary` reactively.\n",
    )


class IncomingMessage(BaseModel):
    """
    Normalized message shape an adapter posts to the
    orchestrator's `POST /v1/chat`. Adapter-specific platform
    details collapse to this universal shape; the orchestrator
    never sees Discord-specific or Slack-specific fields.

    """

    personId: UUID = Field(
        ...,
        description="Sender's `personId` in the identity component. If the\nadapter received a message from an unrecognized\nplatform user, it MUST file a `PendingIdentityLink`\nand not call `/v1/chat` — Eugene only responds to\nknown people.\n",
    )
    conversationId: UUID | None = Field(
        None,
        description='Conversation thread id. Adapters maintain a stable\nmapping from (platform_channel_id, platform_thread_id)\n→ conversationId. Omitted starts a new conversation.\n',
    )
    content: str
    source: MessageSource
    channelContext: list[ChannelContextEntry] | None = Field(
        None,
        description="For channel-mention adapters (Discord channel\nmentions, Slack channels): recent platform messages\npreceding the mention, included for conversational\ngrounding. The orchestrator may surface these to\nhemispheres as ambient context, but only the actual\nmention/reply gets persisted to memory (privacy\ndefault: don't store messages from people who didn't\ninvoke Eugene).\n",
    )


class ModelTemplate(BaseModel):
    """
    A named preset of an ArchitectureConfig (e.g. "small-test-20L",
    "deep-medium-40L" — the migrated CLLM config presets become built-ins).
    Custom templates are clones with overrides.

    """

    name: str
    displayName: str | None = None
    description: str | None = None
    builtin: bool | None = False
    architecture: ArchitectureConfig
    estimatedParamCount: int | None = Field(
        None, description='Read-only; computed from architecture.'
    )


class TrainingRecipe(BaseModel):
    """
    What KIND of training and its method-specific params. UI uses
    ConfigField.showWhen to reveal adapter/quantization blocks only for
    the relevant kind.

    """

    kind: Kind
    baseCheckpoint: CheckpointRef | None = Field(
        None,
        description='Required for continued_pretraining / sft / lora / qlora / dpo.',
    )
    adapter: Adapter | None = Field(
        None, description='LoRA/QLoRA adapter config (kind in [lora, qlora]).'
    )
    quantization: Quantization | None = Field(
        None, description='QLoRA base-weight quantization (kind == qlora).'
    )
    dpoBeta: float | None = Field(None, description='DPO temperature (kind == dpo).')


class TrainingRun(BaseModel):
    """
    One execution of a TrainingProject. Lives inside the trainer service (§2).
    """

    runId: UUID
    projectId: UUID
    status: RunStatus
    createdAt: AwareDatetime
    startedAt: AwareDatetime | None = None
    finishedAt: AwareDatetime | None = None
    currentStep: int | None = Field(None, ge=0)
    totalSteps: int | None = None
    currentEpoch: int | None = Field(None, ge=0)
    tokensSeen: int | None = Field(None, ge=0)
    progressFraction: float | None = Field(None, ge=0.0, le=1.0)
    latestMetrics: TrainingMetricPoint | None = None
    bestValLoss: float | None = None
    checkpointCount: int | None = Field(None, ge=0)
    lastError: str | None = Field(None, description='Populated when status == failed.')


class PipelineStage(BaseModel):
    """
    One stage of a PipelineRun, delegated to a peer component.
    """

    kind: Kind3
    status: PipelineStatus
    component: ComponentKind | None = None
    resourceId: str | None = Field(
        None, description='Id of the underlying resource (e.g. a trainer runId).'
    )
    startedAt: AwareDatetime | None = None
    finishedAt: AwareDatetime | None = None
    detail: str | None = None


class TrainingRunRequest(BaseModel):
    """
    The resolved training spec the coordinator (or UI, for ad-hoc runs)
    hands to the trainer's POST /v1/trainer/runs. Carries everything the
    trainer needs to execute without owning project config; projectId is
    for back-reference / single-active-run enforcement only.

    """

    projectId: UUID | None = None
    architecture: ArchitectureConfig
    recipe: TrainingRecipe
    hyperparameters: Hyperparameters
    hardware: HardwareTopology
    tokenizer: TokenizerRef
    datasets: list[DatasetRef]


class ComponentEntry(BaseModel):
    """
    Declarative half of a Component, used for create / update
    request bodies. Status fields are server-owned and excluded.

    """

    name: str
    kind: ComponentKind
    url: AnyUrl
    spawn: SpawnConfig | None = None
    safeMode: bool | None = False


class ComponentList(BaseModel):
    components: list[Component] = Field(
        ...,
        description='Components in the order they were configured. The first-run\nwizard fills this in; later editing happens via the\nComponents tab.\n',
    )


class MemorySearchResult(BaseModel):
    """
    Ranked list of matching memory entries.
    """

    entries: list[MemorySearchHit]


class TrainingProject(BaseModel):
    """
    The key user-facing abstraction. A reusable, persisted description of
    "a model you are building": what to train, from what data, with which
    recipe and hyperparameters, on which hardware, evaluated how, exported
    where. Runs are executions of a project (one project -> many runs).

    """

    projectId: UUID
    name: str = Field(..., min_length=1)
    description: str | None = None
    goal: TrainingGoal
    createdAt: AwareDatetime
    updatedAt: AwareDatetime | None = None
    modelTemplate: ModelTemplate | None = None
    tokenizer: TokenizerRef | None = None
    datasets: list[DatasetRef] | None = Field(
        None,
        description='Ordered dataset selection (with per-dataset weight + curriculum gate).',
    )
    recipe: TrainingRecipe | None = None
    hyperparameters: Hyperparameters | None = None
    hardware: HardwareTopology | None = None
    evalSuites: list[EvalSuiteRef] | None = None
    exportSettings: ExportSettings | None = None
    latestRunId: UUID | None = None
    latestRunStatus: RunStatus | None = None


class PipelineRun(BaseModel):
    """
    One end-to-end execution of a TrainingProject's pipeline, owned by the
    coordinator. Sequences stages across components (data prep -> tokenizer
    -> training -> eval -> serve), each delegating to a peer component and
    tracking the underlying resource id. One active pipeline per project.

    """

    pipelineRunId: UUID
    projectId: UUID
    status: PipelineStatus
    createdAt: AwareDatetime
    startedAt: AwareDatetime | None = None
    finishedAt: AwareDatetime | None = None
    currentStage: str | None = Field(
        None, description='Kind of the stage currently executing.'
    )
    stages: list[PipelineStage]
    lastError: str | None = None
